export const database = [
  {
    balance: "$3,547.89",
    age: 34,
    name: "John Doe",
    company: "ABC Inc.",
    email: "john.doe@example.com",
    phone: "+1 (123) 456-7890",
    address: "123 Main Street, Cityville, USA",
  },
  {
    balance: "$5,678.45",
    age: 45,
    name: "Jane Smith",
    company: "XYZ Corp",
    email: "jane.smith@example.com",
    phone: "+1 (234) 567-8901",
    address: "456 Elm Street, Townsville, USA",
  },
  {
    balance: "$2,345.67",
    age: 28,
    name: "Michael Johnson",
    company: "123 Industries",
    email: "michael.johnson@example.com",
    phone: "+1 (345) 678-9012",
    address: "789 Oak Avenue, Villagetown, USA",
  },
  {
    balance: "$7,890.12",
    age: 52,
    name: "Emily Brown",
    company: "Brown Enterprises",
    email: "emily.brown@example.com",
    phone: "+1 (456) 789-0123",
    address: "987 Maple Drive, Hamletville, USA",
  },
  {
    balance: "$4,321.98",
    age: 39,
    name: "David Wilson",
    company: "Wilson & Sons",
    email: "david.wilson@example.com",
    phone: "+1 (567) 890-1234",
    address: "654 Pine Road, Suburbia, USA",
  },
  {
    balance: "$6,543.21",
    age: 47,
    name: "Sarah Garcia",
    company: "Garcia Enterprises",
    email: "sarah.garcia@example.com",
    phone: "+1 (678) 901-2345",
    address: "321 Cedar Lane, Countryside, USA",
  },
  {
    balance: "$8,765.43",
    age: 56,
    name: "Daniel Martinez",
    company: "Martinez Ltd.",
    email: "daniel.martinez@example.com",
    phone: "+1 (789) 012-3456",
    address: "852 Birch Street, Riverside, USA",
  },
  {
    balance: "$9,876.54",
    age: 61,
    name: "Olivia Lopez",
    company: "Lopez Group",
    email: "olivia.lopez@example.com",
    phone: "+1 (890) 123-4567",
    address: "159 Willow Avenue, Lakeside, USA",
  },
  {
    balance: "$1,234.56",
    age: 25,
    name: "William Lee",
    company: "Lee Enterprises",
    email: "william.lee@example.com",
    phone: "+1 (901) 234-5678",
    address: "357 Spruce Court, Mountainview, USA",
  },
  {
    balance: "$0.00",
    age: 18,
    name: "Emma Taylor",
    company: "Taylor & Co.",
    email: "emma.taylor@example.com",
    phone: "+1 (012) 345-6789",
    address: "753 Oakwood Lane, Hillside, USA",
  },
];
