export default {
  at: "2024-07-06T19:03:34.311Z",
  products: [
    {
      description: "eu proident aute deserunt",
      name: "officia",
      price: 1520.05,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {},
    {},
    {},
    {},
    {},
    {
      description: "nostrud ex aliqua adipisicing",
      name: "ex",
      price: 615.32,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {
      description: "proident ipsum incididunt excepteur",
      name: "occaecat",
      price: 387.26,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "consequat excepteur cupidatat do",
      name: "eiusmod",
      price: 614.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {
      description: "aliquip mollit mollit cillum",
      name: "elit",
      price: 139.24,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {},
    {},
    {},
    {},
    {
      description: "aute ad ea in",
      name: "ipsum",
      price: 675.91,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: "incididunt aliquip cillum labore",
      name: "incididunt",
      price: 1826.43,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: "elit sit excepteur proident",
      name: "commodo",
      price: 368.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "in laboris commodo ea",
      name: "consectetur",
      price: 1422.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit dolore non dolore",
      name: "amet",
      price: 872.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat tempor id aliqua",
      name: "irure",
      price: 1318.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex fugiat culpa dolore",
      name: "ipsum",
      price: 745.01,
      tmpProperty: undefined,
      activePromoId: 50,
    },
    {
      description: "consectetur voluptate fugiat ut",
      name: "labore",
      price: 1060.41,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu pariatur ea nisi",
      name: "elit",
      price: 271.33,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est aliquip in ipsum",
      name: "excepteur",
      price: 330.69,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: "culpa eiusmod laboris laborum",
      name: "veniam",
      price: 298.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor consequat ipsum ut",
      name: "esse",
      price: 1533.91,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: "commodo esse velit est",
      name: "consectetur",
      price: 515.66,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: "amet esse eiusmod quis",
      name: "eu",
      price: 1243.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sit anim aliqua laborum",
      name: "elit",
      price: 902.56,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: "duis minim consectetur magna",
      name: "nostrud",
      price: 1397.53,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: "ut deserunt reprehenderit nulla",
      name: "fugiat",
      price: 310.26,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "commodo sunt incididunt commodo",
      name: "dolore",
      price: 866.18,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: "sunt est aute excepteur",
      name: "dolor",
      price: 301.92,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt occaecat adipisicing nisi",
      name: "pariatur",
      price: 740.17,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: "voluptate culpa eu Lorem",
      name: "minim",
      price: 228.28,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do qui esse fugiat",
      name: "magna",
      price: 1510.41,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "Lorem sit est pariatur",
      name: "ut",
      price: 702.48,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "et sit velit minim",
      name: "esse",
      price: 652.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum et in sunt",
      name: "Lorem",
      price: 457.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad laborum aliquip minim",
      name: "anim",
      price: 468.18,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "consectetur tempor laborum aliquip",
      name: "non",
      price: 216.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex incididunt reprehenderit voluptate",
      name: "ea",
      price: 797.2,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore ut pariatur enim",
      name: "nostrud",
      price: 1577.82,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: "dolor anim excepteur id",
      name: "amet",
      price: 961.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ipsum nulla cillum laboris",
      name: "est",
      price: 782.21,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "minim aute magna sunt",
      name: "ex",
      price: 540.27,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: "velit commodo ullamco in",
      name: "reprehenderit",
      price: 175.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex laborum qui mollit",
      name: "reprehenderit",
      price: 855.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor quis ea consectetur",
      name: "anim",
      price: 1471.2,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est sint excepteur et",
      name: "aliquip",
      price: 1022.06,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "in minim eiusmod deserunt",
      name: "non",
      price: 1696.39,
      tmpProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "cupidatat pariatur enim Lorem",
      name: "duis",
      price: 1276.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consectetur dolore officia consequat",
      name: "ipsum",
      price: 452.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "proident quis ea ipsum",
      name: "ex",
      price: 1503.09,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: "dolore ea occaecat magna",
      name: "eiusmod",
      price: 1517.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "tempor dolor sit laborum",
      name: "sint",
      price: 1129.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "deserunt dolore dolore aliquip",
      name: "consectetur",
      price: 885.63,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: "aliqua nisi in magna",
      name: "anim",
      price: 241.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi incididunt ut duis",
      name: "consectetur",
      price: 623.4,
      tmpProperty: undefined,
      activePromoId: 75,
    },
    {
      description: "enim adipisicing tempor ut",
      name: "ipsum",
      price: 1467.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim ut et et",
      name: "elit",
      price: 1759.55,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "Lorem id nulla labore",
      name: "ut",
      price: 1065.2,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "labore do magna aute",
      name: "fugiat",
      price: 1411.15,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {
      description: "anim reprehenderit commodo est",
      name: "nostrud",
      price: 1270.22,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "excepteur commodo dolore exercitation",
      name: "fugiat",
      price: 1852.45,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu nulla reprehenderit laboris",
      name: "ad",
      price: 159.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate nulla qui deserunt",
      name: "aliqua",
      price: 1448.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore nisi ad dolore",
      name: "tempor",
      price: 272.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam eiusmod ipsum veniam",
      name: "do",
      price: 1078.15,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "ea est exercitation ullamco",
      name: "veniam",
      price: 1989.14,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "tempor mollit anim labore",
      name: "veniam",
      price: 1697.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua duis nostrud commodo",
      name: "aliquip",
      price: 1904.74,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: "dolor nostrud cupidatat nostrud",
      name: "consectetur",
      price: 719.25,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: "labore excepteur tempor eiusmod",
      name: "exercitation",
      price: 1689.27,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: "anim nulla velit anim",
      name: "commodo",
      price: 112.59,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "proident ex non duis",
      name: "ipsum",
      price: 1013.57,
      tmpProperty: undefined,
      activePromoId: 84,
    },
    {
      description: "dolor non excepteur do",
      name: "nisi",
      price: 1737.18,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "veniam enim amet excepteur",
      name: "ea",
      price: 1099.94,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: "mollit incididunt ea quis",
      name: "quis",
      price: 829.26,
      tmpProperty: undefined,
      activePromoId: 47,
    },
    {
      description: "deserunt voluptate duis laboris",
      name: "Lorem",
      price: 1519.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "in exercitation nisi non",
      name: "incididunt",
      price: 1008.92,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit commodo eiusmod dolore",
      name: "veniam",
      price: 732.14,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "duis quis cupidatat laborum",
      name: "est",
      price: 1440.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi culpa velit excepteur",
      name: "voluptate",
      price: 1551.5,
      tmpProperty: undefined,
      activePromoId: 20,
    },
    {
      description: "aliquip aliquip et duis",
      name: "id",
      price: 247.31,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit labore cillum labore",
      name: "eu",
      price: 771.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad velit ut sint",
      name: "esse",
      price: 504.24,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "proident culpa amet nulla",
      name: "proident",
      price: 551.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod esse occaecat cillum",
      name: "et",
      price: 1252.56,
      tmpProperty: undefined,
      activePromoId: 82,
    },
    {
      description: "do est nisi irure",
      name: "consectetur",
      price: 620.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis anim enim id",
      name: "est",
      price: 1619.78,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: "duis tempor sunt laboris",
      name: "consequat",
      price: 1081.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum fugiat anim nostrud",
      name: "aliquip",
      price: 1831.95,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: "incididunt cillum magna elit",
      name: "aute",
      price: 165.43,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "occaecat ex id dolore",
      name: "in",
      price: 773.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem ex sunt sunt",
      name: "adipisicing",
      price: 1764.35,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: "incididunt ea Lorem nisi",
      name: "anim",
      price: 465.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor eiusmod eiusmod velit",
      name: "exercitation",
      price: 312.19,
      tmpProperty: undefined,
      activePromoId: 50,
    },
    {
      description: "esse tempor dolore non",
      name: "exercitation",
      price: 370.37,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: "laborum nisi nostrud sint",
      name: "adipisicing",
      price: 954.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure dolore voluptate ea",
      name: "aliqua",
      price: 641.69,
      tmpProperty: undefined,
      activePromoId: 20,
    },
    {
      description: "ea duis veniam excepteur",
      name: "velit",
      price: 1173.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia id dolore eiusmod",
      name: "duis",
      price: 166.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor in consequat aute",
      name: "reprehenderit",
      price: 544.57,
      tmpProperty: undefined,
      activePromoId: 55,
    },
    {
      description: "laboris veniam non Lorem",
      name: "fugiat",
      price: 1418.14,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "magna irure deserunt elit",
      name: "elit",
      price: 1713.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sit sunt esse magna",
      name: "labore",
      price: 639.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit eu ullamco elit",
      name: "cillum",
      price: 429.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem ipsum duis consequat",
      name: "cupidatat",
      price: 222.55,
      tmpProperty: undefined,
      activePromoId: 42,
    },
  ],
};
